In [3]:
import numpy as np
import math


In [4]:
# quest 1
def compute_vector_length(vector):
    return math.sqrt(np.sum(vector**2))

vector = np.array([-2, 4, 9, 21])
compute_vector_length(vector)

23.280893453645632

In [5]:
# quest 2
def compute_dot_product(vector1, vector2):
    return vector1@vector2

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1,  0])

compute_dot_product(v1, v2)

4

In [6]:
# quest 3
x = np.array([[1, 2] ,[3, 4]])
k = np.array([1, 2])
print('result \n', x.dot(k))


result 
 [ 5 11]


In [7]:
# quest 4
x = np.array([[-1, 2],[3, -4]])
k = np.array([1, 2])
print('result \n', x.dot(k))


result 
 [ 3 -5]


In [8]:
# quest 5
def matrix_multi_vector(matrix, vector):
    return matrix @ vector

m = np.array([[-1, 1, 1],[0, -4, 9]])
v = np.array([0, 2, 1])
matrix_multi_vector(m, v)


array([3, 1])

In [9]:
# quest 6
def matrix_multi_matrix(matrix_1, matrix_2):
    return matrix_1 @ matrix_2

m1 = np.array([[0, 1, 2],[2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0,-1]])
matrix_multi_matrix(m1, m2)

array([[  6,  -1],
       [-16, -10]])

In [10]:
# quest 7
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
m1@m2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [11]:
# quest 8
m1 = np.eye(2)
m1 = np.reshape(m1, (-1,4))[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
m1@m2


array([5., 5., 5., 5.])

In [12]:
m2@m1


array([2., 4., 6., 8.])

In [13]:
# quest 9
m1 = np.array([[1, 2],[3, 4]])
m1 = np.reshape(m1, (-1,4), "F")
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
m1@m2

array([[29, 29, 29, 29]])

In [65]:
# quest 10
def transform_matrix(matrix):
    a, b = matrix[0][0], matrix[0][1]
    c, d = matrix[1][0], matrix[1][1]
    transformed_matrix = [[d, -b], [-c, a]]
    return transformed_matrix

def inverse_matrix(matrix):

    # Calculate the determinant
    det = np.linalg.det(matrix)
    if det == 0:
        raise ValueError("Matrix is not invertible")


    temp = transform_matrix(matrix)
    # inverse = matrix.T * temp_1 / det

    return  temp/det

m1 = np.array([[-2, 6], [8, -4]])
inverse_matrix(m1)

array([[0.1 , 0.15],
       [0.2 , 0.05]])

In [67]:
# quest 12
def compute_cosine(v1, v2):
  norm_v1 = np.linalg.norm(v1)
  norm_v2 = np.linalg.norm(v2)
  return np.dot(v1, v2) / (norm_v1 * norm_v2)

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
compute_cosine(x,y)

0.5773502691896257